name: CI

on:
  pull_request:
    branches:
      - dev

  push:
    branches:
      - dev
      - main

env:
  RPC_URL: ${{ vars.RPC_URL }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.6.5"

      - name: Cairo lint
        run: scarb fmt --check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.6.5"

      - name: Run Build
        run: scarb build

  test:
    name: Test
    runs-on: ubuntu-latest
    environment: gostarkme
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.6.5"

      - name: Set up Snforge
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.27.0"

      - name: Substitute RPC URL in Scarb.toml
        run: |
          if [ -z "$RPC_URL" ]; then
            echo "RPC_URL is not defined. Using blast."
            sed -i "s|\$RPC_URL|https://starknet-mainnet.public.blastapi.io/rpc/v0_7|g" Scarb.toml
          else
            sed -i "s|\$RPC_URL|$RPC_URL|g" Scarb.toml
          fi

      - name: Run tests
        run: |
          # Capture the output of snforge test
          output=$(snforge test 2>&1 || true)

          echo "Running all tests sequentially:"
          test_names=$(echo "$output" | grep "tests::" | awk '{print $2}')

          if [ -n "$test_names" ]; then
              while IFS= read -r test; do
                  echo "Running: snforge test $test"
                  snforge test "$test"
                  if [ $? -ne 0 ]; then
                          echo "Test $test failed."
                  fi
              done <<< "$test_names"
          else
              echo "No tests found."
          fi
